theme: minima
title: 我的中文不好
author: noradgd
description: Welcome to my page! I'm doing a tutorial on Github. 
![Language learning meme](https://i.pinimg.com/236x/f8/2d/fa/f82dfa1aa4cb1538b140ba90ab82b250.jpg)
